services:
  mc_gtnh:
    image: glitchless/gli_mc_gtnh:8
    restart: unless-stopped
    ports:
      - "25567:25565"
    environment:
      MC_RAM: "16G"
    volumes:
      - ./world:/app/world
      - ./logs:/app/logs
      - ./backups:/app/backups
      - ./config/telegrambridge.cfg:/app/config/telegrambridge.cfg
      - ./config/glitchlessauth.cfg:/app/config/glitchlessauth.cfg
